### ISSUE TITLE
snmp::session->max_msg_size(...) can cause problems with some snmpd implimentations

### ISSUE THREAD

**Issue by dhoffend** [lausser/GLPlugin#6]
I found a bsd based network appliance on which the snmpd daemon reacts with a memory leak until it crashes due to no more memory available.

This happens when you increase the max snmp message size during snmp session initialization. When commenting out the comment in question the daemon performs as expected without memory leak. This only happens when executing a snmpwalk (normal gets are okay) after the msg size has been increased. Also the snmp performance was lower compared to no adjusted msg size.

I'm not sure if it's a good decision to always increase the max_msg_size to 4times its size. If this increase is only needed in rare situations maybe it would be an alternative to offer a commandline parameter instead of automatic enabling it even the remote size could have problems with it.

btw. the appliance vendor is contacted

The line in question:
https://github.com/lausser/GLPlugin/blob/master/lib/Monitoring/GLPlugin/SNMP.pm#L946

```
my $max_msg_size = $session->max_msg_size();
$session->max_msg_size(4 * $max_msg_size);
$Monitoring::GLPlugin::SNMP::session = $session;
```

**Comment by lausser** [comment]
GLPlugin is the base of our customer installations. max_msg_size's value fits all installations, after there were a lot of issues in the past. And, sorry, as stability of my customers' environments is the only thing that counts for me,  am not willing to change anything here neither to discuss anything here.

**Comment by dhoffend** [comment]
I'm fine with this. Problems with single problematic devices while everything else works fine isn't the problem of the library. This is something which has do be dealt with on device/plugin level.

Since I don't know the reason about some of the internal settings I hope you don't mind looking at it or reporting things that I stumpling over.

And for the record: the workaround for the device/snmpd in question was to create a custom my-plugin that resets the max_msg_size() back to it's original value of 1472 and then doing the get object_tables calls / calling the subsystems. (If somebody else is having problems).

Thanks :+1:
